language: go

go:
  - 1.8.x
  - tip
  
# whitelist
branches:
  only:
  - master
  - stable 

script: 
  - go get -t -v ./...
  - go vet ./...
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://hooks.pubu.im/services/3wp9q4yqlzm8fxr